module CMIS
  import org.apache.chemistry.opencmis.commons.enums.Action
  import org.apache.chemistry.opencmis.commons.enums.AclPropagation
  import org.apache.chemistry.opencmis.commons.enums.BaseTypeId
  import org.apache.chemistry.opencmis.commons.enums.CapabilityAcl
  import org.apache.chemistry.opencmis.commons.enums.VersioningState
  import org.apache.chemistry.opencmis.commons.enums.UnfileObject
  import org.apache.chemistry.opencmis.commons.enums.BindingType
  import org.apache.chemistry.opencmis.commons.enums.CapabilityChanges
  import org.apache.chemistry.opencmis.commons.enums.CapabilityContentStreamUpdates
  import org.apache.chemistry.opencmis.commons.enums.CapabilityJoin
  import org.apache.chemistry.opencmis.commons.enums.CapabilityQuery
  import org.apache.chemistry.opencmis.commons.enums.CapabilityRenditions
  import org.apache.chemistry.opencmis.commons.enums.Cardinality
  import org.apache.chemistry.opencmis.commons.enums.ChangeType
  import org.apache.chemistry.opencmis.commons.enums.ContentStreamAllowed
  import org.apache.chemistry.opencmis.commons.enums.DateTimeResolution
  import org.apache.chemistry.opencmis.commons.enums.DecimalPrecision
  import org.apache.chemistry.opencmis.commons.enums.ExtensionLevel
  import org.apache.chemistry.opencmis.commons.enums.IncludeRelationships
  import org.apache.chemistry.opencmis.commons.enums.PropertyType
  import org.apache.chemistry.opencmis.commons.enums.RelationshipDirection
  import org.apache.chemistry.opencmis.commons.enums.SupportedPermissions
  import org.apache.chemistry.opencmis.commons.enums.UnfileObject
  import org.apache.chemistry.opencmis.commons.enums.Updatability
end